name: Build TopSkyMaps

on:
  push:
    branches:
      - main
    paths:
      - '.data/TopSkyMaps/**'

concurrency:
  group: map-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Concatenate and clean files
      run: |
        python .github/workflows/concatenate_topskymaps.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add 'OMAE/Plugins/TopSky/TopSky Aerodrome North/TopSkyMaps.txt'
        git add 'OMAE/Plugins/TopSky/TopSky Aerodrome South/TopSkyMaps.txt'
        git add 'OMAE/Plugins/TopSky/TopSky Aerodrome Maktoum/TopSkyMaps.txt'
        git add 'OMAE/Plugins/TopSky/TopSky Enroute/TopSkyMaps.txt'
        git add 'OMAE/Plugins/TopSky/TopSky CTA Abu Dhabi/TopSkyMaps.txt'
        git add 'OMAE/Plugins/TopSky/TopSky CTA Dubai/TopSkyMaps.txt'
        git add 'OMAE/Plugins/TopSky/TopSky CTA Military/TopSkyMaps.txt'
        git add 'OMAE/Plugins/TopSky/TopSky CTA/TopSkyMaps.txt'
        git commit -m 'Update TopSkyMaps files'
        git push

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Upload cleaned files
        path: |
          OMAE/Plugins/TopSky/TopSky Aerodrome North/TopSkyMaps.txt
          OMAE/Plugins/TopSky/TopSky Aerodrome South/TopSkyMaps.txt
          OMAE/Plugins/TopSky/TopSky Aerodrome Maktoum/TopSkyMaps.txt
          OMAE/Plugins/TopSky/TopSky Enroute/TopSkyMaps.txt
          OMAE/Plugins/TopSky/TopSky CTA Abu Dhabi/TopSkyMaps.txt
          OMAE/Plugins/TopSky/TopSky CTA Dubai/TopSkyMaps.txt
          OMAE/Plugins/TopSky/TopSky CTA Military/TopSkyMaps.txt
          OMAE/Plugins/TopSky/TopSky CTA/TopSkyMaps.txt
          
