name: Build Ground Radar Plugin Maps

on:
  push:
    branches:
      - main
    paths:
      - '.data/GroundRadarPluginMaps/**'

concurrency:
  group: map-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Concatenate and clean files
      run: |
        python .github/workflows/concatenate_GRmaps.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add 'OMAE/Plugins/Ground Radar Plugin/GRpluginMaps.txt'
        git add 'OMAE/Plugins/Ground Radar Plugin/GRpluginStands.txt'
        git commit -m 'Update Ground Radar Plugin files'
        git push

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Upload cleaned files
        path: |
          OMAE/Plugins/Ground Radar Plugin/GRpluginMaps.txt
          OMAE/Plugins/Ground Radar Plugin/GRpluginStands.txt
          
